<?xml version="1.0"?>
<!DOCTYPE announcement [
<!ELEMENT announcement (metadata , items)>
<!ELEMENT metadata (version)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT items (group | evidence)+>
<!ELEMENT group (group-name , group-desc , add? , remove?)>
<!ELEMENT group-name (#PCDATA)>
<!ELEMENT group-desc (#PCDATA)>
<!ELEMENT add (company)+>
<!ELEMENT remove (company)+>
<!ELEMENT evidence (title , description , categories , source , links , companies , reviews)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT categories (category)*>
<!ELEMENT category (category-name , category-rating? , subcategory-name? , subcategory-rating?)>
<!ELEMENT category-name (#PCDATA)>
<!ELEMENT category-rating (#PCDATA)>
<!ELEMENT subcategory-name (#PCDATA)>
<!ELEMENT subcategory-rating (#PCDATA)>
<!ELEMENT source (link)>
<!ELEMENT link (link-text , url , date)>
<!ELEMENT link-text (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT links (link)*>
<!ELEMENT companies (company)+>
<!ELEMENT company (normalized , tagged , address , GCPs , values)>
<!ELEMENT normalized (#PCDATA)>
<!ELEMENT tagged (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT GCPs (GCP)*>
<!ELEMENT GCP (#PCDATA)>
<!ELEMENT values (value)+>
<!ELEMENT value (value-name , score)>
<!ELEMENT value-name (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT reviews (review)+>
<!ELEMENT review (reviewer , date)>
<!ELEMENT reviewer (#PCDATA)>
]>
<announcement>
  <metadata>
    <version>bLeaf 0.10</version>
  </metadata>
  <items>
    <evidence>
      <title>Federal prosecutors are considering manslaughter charges against BP for the Deepwater Horizon oil spill in the Gulf of Mexico that</title>
      <description>
Federal prosecutors are considering manslaughter charges against BP for the Deepwater Horizon oil spill in the Gulf of Mexico that released a total of 4.9 million barrels of crude oil and lasted 87 days; the initial rig explosion also killed 11 workers. Charging individuals for manslaughter involved in the incident is not typical but expected to have a significant deterrent effect, especially in environmental safety cases. BP has committed $20 billion to settle claims by those hurt by the oil spill and has already paid out $4 billion. However, BP stock fell 2.2 percent in London due to talk of the potential charges.
</description>
      <categories>
        <category>
          <category-name>Environment</category-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 196</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=196</url>
          <date>20111026113648</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>Business Week</link-text>
          <url>http://http://www.businessweek.com/news/2011-03-29/bp-is-said-to-face-u-s-review-for-manslaughter-charges.html</url>
          <date/>
        </link>
        <link>
          <link-text>www.bp.com</link-text>
          <url>http://www.bp.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized/>
          <tagged>BP</tagged>
          <address/>
          <GCPs/>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>
          <reviewer>insight</reviewer>
          <date>20111023T171759Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T210157Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T210853Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111026T153647Z</date>
        </review>
      </reviews>
    </evidence>
    <evidence>
      <title>On the 2005 Computer Report Card, published jointly by the Computer TakeBack Campaign and the Silicon Valley Toxics Coalition, App</title>
      <description>
On the 2005 Computer Report Card, published jointly by the Computer TakeBack Campaign and the Silicon Valley Toxics Coalition, Apple received a score of 17 for their policies regarding electronics take back, disposal procedures and the materials used in their computers. Apple s score was better than Acer or Gateway s, slightly worse than Sony and IBM, and trailed HP and Dell by wide margins.
</description>
      <categories>
        <category>
          <category-name>Environment</category-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 186</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=186</url>
          <date>20111025171006</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>Silicon Valley Toxics Coalition</link-text>
          <url>http://svtc.etoxics.org/site/PageServer?pagename=svtc_computer_report_card</url>
          <date/>
        </link>
        <link>
          <link-text>www.apple.com</link-text>
          <url>http://www.apple.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized>acer incorporated</normalized>
          <tagged>Acer</tagged>
          <address/>
          <GCPs>
            <GCP>0099802</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>acer america corporation</normalized>
          <tagged>Acer</tagged>
          <address/>
          <GCPs>
            <GCP>0750519</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Acer America Corporation</normalized>
          <tagged>Acer</tagged>
          <address>CA
2641 Orchard Parkway
95134 
San Jose
United States</address>
          <GCPs>
            <GCP>0750519</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>apple computer, inc.</normalized>
          <tagged>Apple</tagged>
          <address/>
          <GCPs>
            <GCP>0718908</GCP>
            <GCP>0885909</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>0</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>dell u.s.a. l.p.</normalized>
          <tagged>Dell</tagged>
          <address/>
          <GCPs>
            <GCP>0744696</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>+1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized/>
          <tagged>Gateway</tagged>
          <address/>
          <GCPs/>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized/>
          <tagged>H.P.</tagged>
          <address/>
          <GCPs/>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score/>
            </value>
          </values>
        </company>
        <company>
          <normalized>IBM Corporation</normalized>
          <tagged>IBM</tagged>
          <address>NY
1 New Orchard Rd.
10504-1722 
Armonk
United States</address>
          <GCPs>
            <GCP>0883436</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>0</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>sony-bmg</normalized>
          <tagged>Sony</tagged>
          <address/>
          <GCPs>
            <GCP>0743211</GCP>
            <GCP>0743212</GCP>
            <GCP>0743213</GCP>
            <GCP>0743214</GCP>
            <GCP>0743215</GCP>
            <GCP>0743216</GCP>
            <GCP>0743217</GCP>
            <GCP>0743218</GCP>
            <GCP>0828765</GCP>
            <GCP>0828766</GCP>
            <GCP>0828767</GCP>
            <GCP>0828768</GCP>
            <GCP>0886970</GCP>
            <GCP>0886971</GCP>
            <GCP>0888880</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>0</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>sony bmg</normalized>
          <tagged>Sony</tagged>
          <address/>
          <GCPs>
            <GCP>9416333</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>0</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Sony-Bmg</normalized>
          <tagged>Sony</tagged>
          <address>NY
550 Madison Ave
10022 
New York
United States</address>
          <GCPs>
            <GCP>0886443</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>0</score>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>
          <reviewer>insight</reviewer>
          <date>20111023T171819Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T210959Z</date>
        </review>
      </reviews>
    </evidence>
    <evidence>
      <title>&#x2022; UAL Corporation received a score of 88 for the second year in a row on the Human Rights Campaign 2009 Corporate Equality Index w</title>
      <description>
UAL Corporation received a score of 88 for the second year in a row on the Human Rights Campaign 2009 Corporate Equality Index which rates large corporations on policies that affect their gay, lesbian, bisexual and transgender employees, consumers and investors. The HRC Corporate Equality Index rates companies on a scale of 0 to 100 percent.
</description>
      <categories>
        <category>
          <category-name>Human Rights</category-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 401</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=401</url>
          <date>20111026114119</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>Human Rights Campaign</link-text>
          <url>http://www.hrc.org/documents/HRC_Corporate_Equality_Index_2009.pdf</url>
          <date/>
        </link>
        <link>
          <link-text>www.united.com</link-text>
          <url>http://www.united.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized/>
          <tagged>United Airlines</tagged>
          <address/>
          <GCPs/>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score/>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>
          <reviewer>insight</reviewer>
          <date>20111023T171836Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T211320Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111026T154118Z</date>
        </review>
      </reviews>
    </evidence>
    <evidence>
      <title>The Nigerian government accepted an offer to settle its $5 billion lawsuit against Pfizer out of court.</title>
      <description>
The Nigerian government accepted an offer to settle its $5 billion lawsuit against Pfizer out of court.  The drug maker was being sued for punitive damages for allegedly illegally testing its antibiotic Trovan on children during a 1996 meningitis epidemic.  According to the Nigerian government and families of the victims, at least 96 children were either killed or suffered severe neurological injury as a result of the administration of the experimental drug.  A separate lawsuit filed in New York by the families was allowed to move forward in January 2009.
</description>
      <categories>
        <category>
          <category-name>Human Rights</category-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 391</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=391</url>
          <date>20111026124038</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>Tide News</link-text>
          <url>http://www.thetidenews.com/article.aspx?qrDate=01/28/2009&amp;qrTitle=Fed%20Govt,%20Pfizer%20opt%20for%20out-of-court%20settlement&amp;qrColumn=NATION</url>
          <date/>
        </link>
        <link>
          <link-text>www.pfizer.com</link-text>
          <url>http://www.pfizer.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized>pfizer inc./consumer health care</normalized>
          <tagged>Pfizer</tagged>
          <address/>
          <GCPs>
            <GCP>0074300</GCP>
            <GCP>0086414</GCP>
            <GCP>0305012</GCP>
            <GCP>0305013</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>pfizer inc./pfipharmecs div</normalized>
          <tagged>Pfizer</tagged>
          <address/>
          <GCPs>
            <GCP>0071404</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>pfizer inc.</normalized>
          <tagged>Pfizer</tagged>
          <address/>
          <GCPs>
            <GCP>0087219</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>pfizer consumer healthcare</normalized>
          <tagged>Pfizer</tagged>
          <address/>
          <GCPs>
            <GCP>9310059</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>pfizer consumer health products company</normalized>
          <tagged>Pfizer</tagged>
          <address/>
          <GCPs>
            <GCP>5010123</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>pfizer pty ltd</normalized>
          <tagged>Pfizer</tagged>
          <address/>
          <GCPs>
            <GCP>9313212</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Pfizer Inc.</normalized>
          <tagged>Pfizer</tagged>
          <address>NY
235 E 42nd St
10017 
New York
United States</address>
          <GCPs>
            <GCP>0087219</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Pfizer Inc./Pfipharmecs Div</normalized>
          <tagged>Pfizer</tagged>
          <address>MO
1 SE Pfizer Way
64081 
Lees Summit
United States</address>
          <GCPs>
            <GCP>0071404</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Pfizer Consumer Healthcare</normalized>
          <tagged>Pfizer</tagged>
          <address>NY
235 East 42nd St.
10017 
New York
United States</address>
          <GCPs>
            <GCP>030573</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>
          <reviewer>insight</reviewer>
          <date>20111023T172155Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T211338Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111026T164037Z</date>
        </review>
      </reviews>
    </evidence>
    <evidence>
      <title>Time Warner Cable increased its rates without any real reason.</title>
      <description>
Time Warner Cable increased its rates without any real reason.  The Communications Workers of America Union claims that the company is putting more money into executives pockets and leaving lower level employees with nothing.  In 2008 there were 35 employees without a pension plan.   
Timer Warner Cable says they are increasing their rates due to higher demand for premium packages and the rising cost of fuel.  They also claim that the reason why the CWA is protesting is because the President of the union is an employee of Verizon, which is a rival of Time Warner Cable.
</description>
      <categories>
        <category>
          <category-name>Business Practices </category-name>
          <subcategory-name>Workers Rights</subcategory-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 345</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=345</url>
          <date>20111025171433</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>NBC-WKTV</link-text>
          <url>http://http://www.wktv.com/news/local/17155736.html</url>
          <date/>
        </link>
        <link>
          <link-text>www.timewarner.com</link-text>
          <url>http://www.timewarner.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized>Time Warner Cable</normalized>
          <tagged>Time Warner</tagged>
          <address>MN
9705 Data Park
55343-9119 
Minnetonka
United States</address>
          <GCPs>
            <GCP>083633600</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Time Warner Interactive Group</normalized>
          <tagged>Time Warner</tagged>
          <address>NY
1 Time Warner Center
10019 
New York
United States</address>
          <GCPs>
            <GCP>0099171</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>
          <reviewer>insight</reviewer>
          <date>20111023T172206Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T211431Z</date>
        </review>
      </reviews>
    </evidence>
    <evidence>
      <title>Forest Ethics rated retailers on their paper use in 2009 in terms of use of Forest Stewardship Council certified paper, recycled c</title>
      <description>
Forest Ethics rated retailers on their paper use in 2009 in terms of use of Forest Stewardship Council certified paper, recycled content, paper reduction and the avoidance of paper from endangered forests. Forest Ethics judges the retailer s paper choice in its catalogs and other mailings to form a  Naughty/Nice List  of a total of 21 companies. Sears earned a  naughty  rating because although they finally established a paper policy, it is mostly greenwashing.
</description>
      <categories>
        <category>
          <category-name>Environment</category-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 286</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=286</url>
          <date>20111025171451</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>Forest Ethics</link-text>
          <url>http://http://forestethics.org/downloads/naughtynicelist2009_Ultimate.pdf</url>
          <date/>
        </link>
        <link>
          <link-text>www.sears.com</link-text>
          <url>http://www.sears.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized>sears, roebuck and co.</normalized>
          <tagged>Sears</tagged>
          <address/>
          <GCPs>
            <GCP>0633815</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Sears, Roebuck and Co.</normalized>
          <tagged>Sears</tagged>
          <address>IL
3333 Beverly Road
E3-292B
60179 
Hoffman Estates
United States</address>
          <GCPs>
            <GCP>0883967</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>
          <reviewer>insight</reviewer>
          <date>20111023T172220Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T211450Z</date>
        </review>
      </reviews>
    </evidence>
    <evidence>
      <title>An internal Wal-Mart memo to the board of directors was published containing controversial proposals for keeping company health ca</title>
      <description>
An internal Wal-Mart memo to the board of directors was published containing controversial proposals for keeping company health care spending low while simultaneously repairing its damaged public image.  Proposals ranged from making employees withstand a longer waiting period before joining the company's policy to changing all job descriptions to include some level of physical activity, thereby ensuring the hiring of only healthier workers.
</description>
      <categories>
        <category>
          <category-name>Politics</category-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 306</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=306</url>
          <date>20111025171517</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>National Public Radio (NPR)</link-text>
          <url>http://www.npr.org/templates/story/story.php?storyId=4975919</url>
          <date/>
        </link>
        <link>
          <link-text>www.walmartstores.com</link-text>
          <url>http://www.walmartstores.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized>wal-mart stores, inc.</normalized>
          <tagged>Wal-Mart</tagged>
          <address/>
          <GCPs>
            <GCP>0078742</GCP>
            <GCP>0605388</GCP>
            <GCP>0681131</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Wal-Mart Stores, Inc.</normalized>
          <tagged>Wal-Mart</tagged>
          <address>AR
702 S.W. 8th St
MS 16
72716 
Bentonville
United States</address>
          <GCPs>
            <GCP>0078742</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>
          <reviewer>insight</reviewer>
          <date>20111023T172225Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T211516Z</date>
        </review>
      </reviews>
    </evidence>
    <evidence>
      <title>According to the Clean Clothes Campaign, &#x201C;Although Fila has a Code of Business Conduct, we have not been able to trace any informa</title>
      <description>
According to the Clean Clothes Campaign,  Although Fila has a Code of Business Conduct, we have not been able to trace any information on how the company actually implements its code. Fila has not joined any multi-stakeholder initiatives on labour standards. Evidence on the ground suggests that the company is far from meeting its ethical commitments.
</description>
      <categories>
        <category>
          <category-name>Business Practices </category-name>
          <subcategory-name>Workers Rights</subcategory-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 224</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=224</url>
          <date>20111025171537</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>Clean Clothes Campaign</link-text>
          <url>http://www.cleanclothes.org/companies/fila.htm</url>
          <date/>
        </link>
        <link>
          <link-text>www.fila.com</link-text>
          <url>http://www.fila.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized>fila usa, inc.</normalized>
          <tagged>Fila</tagged>
          <address/>
          <GCPs>
            <GCP>0633641</GCP>
            <GCP>0723567</GCP>
            <GCP>0731616</GCP>
            <GCP>0791271</GCP>
            <GCP>0791272</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
        <company>
          <normalized>Fila USA, Inc.</normalized>
          <tagged>Fila</tagged>
          <address>MD
930 Ridgebrook Rd., Ste 200
21152
Sparks
United States</address>
          <GCPs>
            <GCP>0723567</GCP>
          </GCPs>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>
          <reviewer>insight</reviewer>
          <date>20111023T172235Z</date>
        </review>
        <review>
          <reviewer>beethoven</reviewer>
          <date>20111025T211532Z</date>
        </review>
      </reviews>
    </evidence>
    <evidence>
      <title>Aetna has agreed to return $5 million to college students who were overcharged by their Aetna insurance plans.</title>
      <description>
Aetna has agreed to return $5 million to college students who were overcharged by their Aetna insurance plans. 73,000 college students will soon be reimbursed for being charged outdated rates. If you believe you are part of the affected group, you can contact an Aetna customer service representative at 866-805-7643.
</description>
      <categories>
        <category>
          <category-name>Politics</category-name>
        </category>
      </categories>
      <source>
        <link>
          <link-text>Green America: Company ID 424</link-text>
          <url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=424</url>
          <date>20111025171559</date>
        </link>
      </source>
      <links>
        <link>
          <link-text>The Consumerist</link-text>
          <url>http://consumerist.com/2009/02/aetna-underpaid-students-settles-for-5-million.html</url>
          <date/>
        </link>
        <link>
          <link-text>http://www.aetna.com</link-text>
          <url>http://http://www.aetna.com</url>
          <date/>
        </link>
      </links>
      <companies>
        <company>
          <normalized/>
          <tagged>Aetna</tagged>
          <address/>
          <GCPs/>
          <values>
            <value>
              <value-name>polarity</value-name>
              <score>-1</score>
            </value>
          </values>
        </company>
      </companies>
      <reviews>
        <review>