<?xml version='1.0' ?>
<!DOCTYPE announcement [
<!ELEMENT announcement (metadata,items)>
<!ELEMENT metadata (version)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT items ((group|evidence)+)>
<!ELEMENT group (group-name,group-desc,add?,remove?)>
<!ELEMENT group-name (#PCDATA)>
<!ELEMENT group-desc (#PCDATA)>
<!ELEMENT add (company+)>
<!ELEMENT remove (company+)>
<!ELEMENT evidence (title,description,categories,sources,links,companies,reviews)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT categories (category*)>
<!ELEMENT category (category-name,category-rating?)>
<!ELEMENT category-name (#PCDATA)>
<!ELEMENT category-rating (#PCDATA)>
<!ELEMENT sources (source+)>
<!ELEMENT source (source-text,url,date)>
<!ELEMENT source-text (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT links (link*)>
<!ELEMENT link (link-text,url)>
<!ELEMENT link-text (#PCDATA)>
<!ELEMENT companies (company+)>
<!ELEMENT company (normalized,tagged,address,GCPs)>
<!ELEMENT normalized (#PCDATA)>
<!ELEMENT tagged (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT GCPs (GCP*)>
<!ELEMENT GCP (#PCDATA)>
<!ELEMENT reviews (review+)>
<!ELEMENT review (reviewer,date)>
<!ELEMENT reviewer (#PCDATA)>
]>
<announcement>
  <metadata>
    <version>bLeaf 0.2</version>
  </metadata>
  <items>
    <evidence>
      <title>Federal prosecutors are considering manslaughter charges against BP for the Deepwater Horizon oil spill in the Gulf of Mexico that</title>
      <description>
	Federal prosecutors are considering manslaughter charges against BP for the Deepwater Horizon oil spill in the Gulf of Mexico that released a total of 4.9 million barrels of crude oil and lasted 87 days; the initial rig explosion also killed 11 workers. Charging individuals for manslaughter involved in the incident is not typical but expected to have a significant deterrent effect, especially in environmental safety cases. BP has committed $20 billion to settle claims by those hurt by the oil spill and has already paid out $4 billion. However, BP stock fell 2.2 percent in London due to talk of the potential charges. 

      </description>
      <categories>
	<category>
	  <category-name>Environment</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 196</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=196</url><date>20111023121801</date></source><source><source-text>Business Week</source-text><url>http://http://www.businessweek.com/news/2011-03-29/bp-is-said-to-face-u-s-review-for-manslaughter-charges.html</url><date>20111023121801</date></source></sources>
	<links><link><link-text>www.bp.com</link-text><url>http://www.bp.com</url></link></links>
      <companies>
	<company>
	  <normalized></normalized>
	  <tagged>BP</tagged>
	  <address></address>
	  <GCPs></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T171759Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>On the 2005 Computer Report Card, published jointly by the Computer TakeBack Campaign and the Silicon Valley Toxics Coalition, App</title>
      <description>
	On the 2005 Computer Report Card, published jointly by the Computer TakeBack Campaign and the Silicon Valley Toxics Coalition, Apple received a score of 17 for their policies regarding electronics take back, disposal procedures and the materials used in their computers. Apple’s score was better than Acer or Gateway’s, slightly worse than Sony and IBM, and trailed HP and Dell by wide margins. 

      </description>
      <categories>
	<category>
	  <category-name>Environment</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 186</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=186</url><date>20111023121823</date></source><source><source-text>Silicon Valley Toxics Coalition</source-text><url>http://svtc.etoxics.org/site/PageServer?pagename=svtc_computer_report_card</url><date>20111023121823</date></source></sources>
	<links><link><link-text>www.apple.com</link-text><url>http://www.apple.com</url></link></links>
      <companies>
	<company>
	  <normalized>acer incorporated</normalized>
	  <tagged>Acer</tagged>
	  <address></address>
	  <GCPs><GCP>0099802</GCP></GCPs>
	</company>
	<company>
	  <normalized>acer america corporation</normalized>
	  <tagged>Acer</tagged>
	  <address></address>
	  <GCPs><GCP>0750519</GCP></GCPs>
	</company>
	<company>
	  <normalized>Acer America Corporation</normalized>
	  <tagged>Acer</tagged>
	  <address>CA
	  2641 Orchard Parkway
	  95134 
	  San Jose
	  United States</address>
	  <GCPs><GCP>0750519</GCP></GCPs>
	</company>
	<company>
	  <normalized>apple computer, inc.</normalized>
	  <tagged>Apple</tagged>
	  <address></address>
	  <GCPs><GCP>0718908</GCP>
	  <GCP>0885909</GCP></GCPs>
	</company>
	<company>
	  <normalized></normalized>
	  <tagged>Gateway</tagged>
	  <address></address>
	  <GCPs></GCPs>
	</company>
	<company>
	  <normalized>IBM Corporation</normalized>
	  <tagged>IBM</tagged>
	  <address>NY
	  1 New Orchard Rd.
	  10504-1722 
	  Armonk
	  United States</address>
	  <GCPs><GCP>0883436</GCP></GCPs>
	</company>
	<company>
	  <normalized>IBM Corporation</normalized>
	  <tagged>IBM</tagged>
	  <address>NY
	  1 New Orchard Rd.
	  10504-1722 
	  Armonk
	  United States</address>
	  <GCPs><GCP>0883436</GCP></GCPs>
	</company>
	<company>
	  <normalized>sony-bmg</normalized>
	  <tagged>Sony</tagged>
	  <address></address>
	  <GCPs><GCP>0743211</GCP>
	  <GCP>0743212</GCP>
	  <GCP>0743213</GCP>
	  <GCP>0743214</GCP>
	  <GCP>0743215</GCP>
	  <GCP>0743216</GCP>
	  <GCP>0743217</GCP>
	  <GCP>0743218</GCP>
	  <GCP>0828765</GCP>
	  <GCP>0828766</GCP>
	  <GCP>0828767</GCP>
	  <GCP>0828768</GCP>
	  <GCP>0886970</GCP>
	  <GCP>0886971</GCP>
	  <GCP>0888880</GCP></GCPs>
	</company>
	<company>
	  <normalized>sony bmg</normalized>
	  <tagged>Sony</tagged>
	  <address></address>
	  <GCPs><GCP>9416333</GCP></GCPs>
	</company>
	<company>
	  <normalized>Sony-Bmg</normalized>
	  <tagged>Sony</tagged>
	  <address>NY
	  550 Madison Ave
	  10022 
	  New York
	  United States</address>
	  <GCPs><GCP>0886443</GCP></GCPs>
	</company>
	<company>
	  <normalized>Sony-Bmg</normalized>
	  <tagged>Sony</tagged>
	  <address>NY
	  550 Madison Ave
	  10022 
	  New York
	  United States</address>
	  <GCPs><GCP>0886443</GCP></GCPs>
	</company>
	<company>
	  <normalized>Sony-Bmg</normalized>
	  <tagged>Sony</tagged>
	  <address>NY
	  550 Madison Ave
	  10022 
	  New York
	  United States</address>
	  <GCPs><GCP>0886443</GCP></GCPs>
	</company>
	<company>
	  <normalized>Sony-Bmg</normalized>
	  <tagged>Sony</tagged>
	  <address>NY
	  550 Madison Ave
	  10022 
	  New York
	  United States</address>
	  <GCPs><GCP>0886443</GCP></GCPs>
	</company>
	<company>
	  <normalized>Sony-Bmg</normalized>
	  <tagged>Sony</tagged>
	  <address>NY
	  550 Madison Ave
	  10022 
	  New York
	  United States</address>
	  <GCPs><GCP>0886443</GCP></GCPs>
	</company>
	<company>
	  <normalized>Sony-Bmg</normalized>
	  <tagged>Sony</tagged>
	  <address>NY
	  550 Madison Ave
	  10022 
	  New York
	  United States</address>
	  <GCPs><GCP>0886443</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T171819Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>• UAL Corporation received a score of 88 for the second year in a row on the Human Rights Campaign 2009 Corporate Equality Index w</title>
      <description>
	• UAL Corporation received a score of 88 for the second year in a row on the Human Rights Campaign 2009 Corporate Equality Index which rates large corporations on policies that affect their gay, lesbian, bisexual and transgender employees, consumers and investors. The HRC Corporate Equality Index rates companies on a scale of 0 to 100 percent. 

      </description>
      <categories>
	<category>
	  <category-name>Human Rights</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 401</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=401</url><date>20111023121847</date></source><source><source-text>Human Rights Campaign</source-text><url>http://www.hrc.org/documents/HRC_Corporate_Equality_Index_2009.pdf</url><date>20111023121847</date></source></sources>
	<links><link><link-text>www.united.com</link-text><url>http://www.united.com</url></link></links>
      <companies>
	<company>
	  <normalized></normalized>
	  <tagged>United Airlines</tagged>
	  <address></address>
	  <GCPs></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T171836Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>The Nigerian government accepted an offer to settle its $5 billion lawsuit against Pfizer out of court.</title>
      <description>
	The Nigerian government accepted an offer to settle its $5 billion lawsuit against Pfizer out of court.  The drug maker was being sued for punitive damages for allegedly illegally testing its antibiotic Trovan on children during a 1996 meningitis epidemic.  According to the Nigerian government and families of the victims, at least 96 children were either killed or suffered severe neurological injury as a result of the administration of the experimental drug.  A separate lawsuit filed in New York by the families was allowed to move forward in January 2009. 

      </description>
      <categories>
	<category>
	  <category-name>Human Rights</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 391</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=391</url><date>20111023122158</date></source><source><source-text>Tide News</source-text><url>http://www.thetidenews.com/article.aspx?qrDate=01/28/2009&amp;qrTitle=Fed%20Govt,%20Pfizer%20opt%20for%20out-of-court%20settlement&amp;qrColumn=NATION</url><date>20111023122158</date></source></sources>
	<links><link><link-text>www.pfizer.com</link-text><url>http://www.pfizer.com</url></link></links>
      <companies>
	<company>
	  <normalized>pfizer inc./consumer health care</normalized>
	  <tagged>Pfizer</tagged>
	  <address></address>
	  <GCPs><GCP>0074300</GCP>
	  <GCP>0086414</GCP>
	  <GCP>0305012</GCP>
	  <GCP>0305013</GCP></GCPs>
	</company>
	<company>
	  <normalized>pfizer inc./pfipharmecs div</normalized>
	  <tagged>Pfizer</tagged>
	  <address></address>
	  <GCPs><GCP>0071404</GCP></GCPs>
	</company>
	<company>
	  <normalized>pfizer inc.</normalized>
	  <tagged>Pfizer</tagged>
	  <address></address>
	  <GCPs><GCP>0087219</GCP></GCPs>
	</company>
	<company>
	  <normalized>pfizer consumer healthcare</normalized>
	  <tagged>Pfizer</tagged>
	  <address></address>
	  <GCPs><GCP>9310059</GCP></GCPs>
	</company>
	<company>
	  <normalized>pfizer consumer health products company</normalized>
	  <tagged>Pfizer</tagged>
	  <address></address>
	  <GCPs><GCP>5010123</GCP></GCPs>
	</company>
	<company>
	  <normalized>pfizer pty ltd</normalized>
	  <tagged>Pfizer</tagged>
	  <address></address>
	  <GCPs><GCP>9313212</GCP></GCPs>
	</company>
	<company>
	  <normalized>Pfizer Inc.</normalized>
	  <tagged>Pfizer</tagged>
	  <address>NY
	  235 E 42nd St
	  10017 
	  New York
	  United States</address>
	  <GCPs><GCP>0087219</GCP></GCPs>
	</company>
	<company>
	  <normalized>Pfizer Inc./Pfipharmecs Div</normalized>
	  <tagged>Pfizer</tagged>
	  <address>MO
	  1 SE Pfizer Way
	  64081 
	  Lees Summit
	  United States</address>
	  <GCPs><GCP>0071404</GCP></GCPs>
	</company>
	<company>
	  <normalized>Pfizer Consumer Healthcare</normalized>
	  <tagged>Pfizer</tagged>
	  <address>NY
	  235 East 42nd St.
	  10017 
	  New York
	  United States</address>
	  <GCPs><GCP>030573</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172155Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>Time Warner Cable increased its rates without any real reason.</title>
      <description>
	Time Warner Cable increased its rates without any real reason.  The Communications Workers of America Union claims that the company is putting more money into executives pockets and leaving lower level employees with nothing.  In 2008 there were 35 employees without a pension plan.  &lt;p&gt;
	Timer Warner Cable says they are increasing their rates due to higher demand for premium packages and the rising cost of fuel.  They also claim that the reason why the CWA is protesting is because the President of the union is an employee of Verizon, which is a rival of Time Warner Cable. 

      </description>
      <categories>
	<category>
	  <category-name>Business Practices | Workers Rights</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 345</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=345</url><date>20111023122213</date></source><source><source-text>NBC-WKTV</source-text><url>http://http://www.wktv.com/news/local/17155736.html</url><date>20111023122213</date></source></sources>
	<links><link><link-text>www.timewarner.com</link-text><url>http://www.timewarner.com</url></link></links>
      <companies>
	<company>
	  <normalized>Time Warner Cable</normalized>
	  <tagged>Time Warner</tagged>
	  <address>MN
	  9705 Data Park
	  55343-9119 
	  Minnetonka
	  United States</address>
	  <GCPs><GCP>083633600</GCP></GCPs>
	</company>
	<company>
	  <normalized>Time Warner Interactive Group</normalized>
	  <tagged>Time Warner</tagged>
	  <address>NY
	  1 Time Warner Center
	  10019 
	  New York
	  United States</address>
	  <GCPs><GCP>0099171</GCP></GCPs>
	</company>
	<company>
	  <normalized>verizon wireless</normalized>
	  <tagged>Verizon</tagged>
	  <address></address>
	  <GCPs><GCP>0840168</GCP></GCPs>
	</company>
	<company>
	  <normalized>Verizon Wireless</normalized>
	  <tagged>Verizon</tagged>
	  <address>NJ
	  Attn: Joe Wiegner
	  1 Verizon Way
	  07920
	  Basking Ridge
	  United States</address>
	  <GCPs><GCP>08401680</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172206Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>Forest Ethics rated retailers on their paper use in 2009 in terms of use of Forest Stewardship Council certified paper, recycled c</title>
      <description>
	Forest Ethics rated retailers on their paper use in 2009 in terms of use of Forest Stewardship Council certified paper, recycled content, paper reduction and the avoidance of paper from endangered forests. Forest Ethics judges the retailer’s paper choice in its catalogs and other mailings to form a “Naughty/Nice List” of a total of 21 companies. Sears earned a “naughty” rating because although they finally established a paper policy, it is mostly greenwashing. 

      </description>
      <categories>
	<category>
	  <category-name>Environment</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 286</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=286</url><date>20111023122221</date></source><source><source-text>Forest Ethics</source-text><url>http://http://forestethics.org/downloads/naughtynicelist2009_Ultimate.pdf</url><date>20111023122221</date></source></sources>
	<links><link><link-text>www.sears.com</link-text><url>http://www.sears.com</url></link></links>
      <companies>
	<company>
	  <normalized>sears, roebuck and co.</normalized>
	  <tagged>Sears</tagged>
	  <address></address>
	  <GCPs><GCP>0633815</GCP></GCPs>
	</company>
	<company>
	  <normalized>Sears, Roebuck and Co.</normalized>
	  <tagged>Sears</tagged>
	  <address>IL
	  3333 Beverly Road
	  E3-292B
	  60179 
	  Hoffman Estates
	  United States</address>
	  <GCPs><GCP>0883967</GCP></GCPs>
	</company>
	<company>
	  <normalized>Sears, Roebuck and Co.</normalized>
	  <tagged>Sears</tagged>
	  <address>IL
	  3333 Beverly Road
	  E3-292B
	  60179 
	  Hoffman Estates
	  United States</address>
	  <GCPs><GCP>0883967</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172220Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>An internal Wal-Mart memo to the board of directors was published containing controversial proposals for keeping company health ca</title>
      <description>
	An internal Wal-Mart memo to the board of directors was published containing controversial proposals for keeping company health care spending low while simultaneously repairing its damaged public image.  Proposals ranged from making employees withstand a longer waiting period before joining the company's policy to changing all job descriptions to include some level of physical activity, thereby ensuring the hiring of only healthier workers. 

      </description>
      <categories>
	<category>
	  <category-name>Politics</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 306</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=306</url><date>20111023122229</date></source><source><source-text>National Public Radio (NPR)</source-text><url>http://www.npr.org/templates/story/story.php?storyId=4975919</url><date>20111023122229</date></source></sources>
	<links><link><link-text>www.walmartstores.com</link-text><url>http://www.walmartstores.com</url></link></links>
      <companies>
	<company>
	  <normalized>wal-mart stores, inc.</normalized>
	  <tagged>Wal-Mart</tagged>
	  <address></address>
	  <GCPs><GCP>0078742</GCP>
	  <GCP>0605388</GCP>
	  <GCP>0681131</GCP></GCPs>
	</company>
	<company>
	  <normalized>Wal-Mart Stores, Inc.</normalized>
	  <tagged>Wal-Mart</tagged>
	  <address>AR
	  702 S.W. 8th St
	  MS 16
	  72716 
	  Bentonville
	  United States</address>
	  <GCPs><GCP>0078742</GCP></GCPs>
	</company>
	<company>
	  <normalized>Wal-Mart Stores, Inc.</normalized>
	  <tagged>Wal-Mart</tagged>
	  <address>AR
	  702 S.W. 8th St
	  MS 16
	  72716 
	  Bentonville
	  United States</address>
	  <GCPs><GCP>0078742</GCP></GCPs>
	</company>
	<company>
	  <normalized>Wal-Mart Stores, Inc.</normalized>
	  <tagged>Wal-Mart</tagged>
	  <address>AR
	  702 S.W. 8th St
	  MS 16
	  72716 
	  Bentonville
	  United States</address>
	  <GCPs><GCP>0078742</GCP></GCPs>
	</company>
	<company>
	  <normalized>Wal-Mart Stores, Inc.</normalized>
	  <tagged>Wal-Mart</tagged>
	  <address>AR
	  702 S.W. 8th St
	  MS 16
	  72716 
	  Bentonville
	  United States</address>
	  <GCPs><GCP>0078742</GCP></GCPs>
	</company>
	<company>
	  <normalized>Wal-Mart Stores, Inc.</normalized>
	  <tagged>Wal-Mart</tagged>
	  <address>AR
	  702 S.W. 8th St
	  MS 16
	  72716 
	  Bentonville
	  United States</address>
	  <GCPs><GCP>0078742</GCP></GCPs>
	</company>
	<company>
	  <normalized>Wal-Mart Stores, Inc.</normalized>
	  <tagged>Wal-Mart</tagged>
	  <address>AR
	  702 S.W. 8th St
	  MS 16
	  72716 
	  Bentonville
	  United States</address>
	  <GCPs><GCP>0078742</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172225Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>According to the Clean Clothes Campaign, “Although Fila has a Code of Business Conduct, we have not been able to trace any informa</title>
      <description>
	According to the Clean Clothes Campaign, “Although Fila has a Code of Business Conduct, we have not been able to trace any information on how the company actually implements its code. Fila has not joined any multi-stakeholder initiatives on labour standards. Evidence on the ground suggests that the company is far from meeting its ethical commitments.” 

      </description>
      <categories>
	<category>
	  <category-name>Business Practices | Workers Rights</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 224</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=224</url><date>20111023122236</date></source><source><source-text>Clean Clothes Campaign</source-text><url>http://www.cleanclothes.org/companies/fila.htm</url><date>20111023122236</date></source></sources>
	<links><link><link-text>www.fila.com</link-text><url>http://www.fila.com</url></link></links>
      <companies>
	<company>
	  <normalized>fila usa, inc.</normalized>
	  <tagged>Fila</tagged>
	  <address></address>
	  <GCPs><GCP>0633641</GCP>
	  <GCP>0723567</GCP>
	  <GCP>0731616</GCP>
	  <GCP>0791271</GCP>
	  <GCP>0791272</GCP></GCPs>
	</company>
	<company>
	  <normalized>Fila USA, Inc.</normalized>
	  <tagged>Fila</tagged>
	  <address>MD
	  930 Ridgebrook Rd., Ste 200
	  21152
	  Sparks
	  United States</address>
	  <GCPs><GCP>0723567</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172235Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>Aetna has agreed to return $5 million to college students who were overcharged by their Aetna insurance plans.</title>
      <description>
	Aetna has agreed to return $5 million to college students who were overcharged by their Aetna insurance plans. 73,000 college students will soon be reimbursed for being charged outdated rates. If you believe you are part of the affected group, you can contact an Aetna customer service representative at 866-805-7643. 

      </description>
      <categories>
	<category>
	  <category-name>Politics</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 424</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=424</url><date>20111023122242</date></source><source><source-text>The Consumerist</source-text><url>http://consumerist.com/2009/02/aetna-underpaid-students-settles-for-5-million.html</url><date>20111023122242</date></source></sources>
	<links><link><link-text>http://www.aetna.com</link-text><url>http://http://www.aetna.com</url></link></links>
      <companies>
	<company>
	  <normalized></normalized>
	  <tagged>Aetna</tagged>
	  <address></address>
	  <GCPs></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172238Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>Environmental Defense published a list of the organizations that have questioned global warming and climate change to which Exxon </title>
      <description>
	Environmental Defense published a list of the organizations that have questioned global warming and climate change to which Exxon funneled money.  Exxon has poured millions of dollars into funding &quot;junk science&quot; around the world. 

      </description>
      <categories>
	<category>
	  <category-name>Environment</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 221</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=221</url><date>20111023122246</date></source><source><source-text>Environmental Defense</source-text><url>http://www.environmentaldefense.org/article.cfm?ContentID=4870</url><date>20111023122246</date></source></sources>
	<links><link><link-text>www.exxon.mobil.com</link-text><url>http://www.exxon.mobil.com</url></link></links>
      <companies>
	<company>
	  <normalized>exxon company, u.s.a.</normalized>
	  <tagged>Exxon</tagged>
	  <address></address>
	  <GCPs><GCP>0077162</GCP></GCPs>
	</company>
	<company>
	  <normalized>Exxon Company, U.S.A.</normalized>
	  <tagged>Exxon</tagged>
	  <address>TX
	  5959 Las Colinas Blvd
	  75039
	  Irving
	  United States</address>
	  <GCPs><GCP>0077162</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172245Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>Ford was rated as the 18th worst polluter on the Political Economy Research Institute's (PERI) Toxic 100 index.</title>
      <description>
	Ford was rated as the 18th worst polluter on the Political Economy Research Institute's (PERI) Toxic 100 index. PERI is an “independent unit of the University of Massachusetts,” that promotes environmental sustainability and human rights through research. The index is based on 2007 EPA Toxics Release Inventory data. PERI's Toxic 100 index ranks the nation's largest companies based on the quantity of their emissions, relative toxicity of chemicals emitted, and proximity to population centers, among other criteria. 

      </description>
      <categories>
	<category>
	  <category-name>Environment</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 226</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=226</url><date>20111023122255</date></source><source><source-text>Political Economy Research Institute (PERI)</source-text><url>http://http://www.peri.umass.edu/Toxic-100-Index.430.0.html</url><date>20111023122255</date></source></sources>
	<links><link><link-text>www.ford.com</link-text><url>http://www.ford.com</url></link></links>
      <companies>
	<company>
	  <normalized>ford motor co/parts   service</normalized>
	  <tagged>Ford</tagged>
	  <address></address>
	  <GCPs><GCP>0031508</GCP>
	  <GCP>0084422</GCP></GCPs>
	</company>
	<company>
	  <normalized>ford motor company/special vehicle oper.</normalized>
	  <tagged>Ford</tagged>
	  <address></address>
	  <GCPs><GCP>0756122</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172253Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>Exxon-Mobil was ranked the fifth “greenest” oil company out of the top 10 leading US oil corporations by Greenopia in 2011.</title>
      <description>
	Exxon-Mobil was ranked the fifth “greenest” oil company out of the top 10 leading US oil corporations by Greenopia in 2011. Exxon publishes a decent sustainability report but the data for oil spill volume is not included. Greenopia also commends Exxon’s relatively low water consumption involved in its oil production and notes that Exxon has had a “very small” number of spills in regards to the volume of its oil production. However, Greenopia criticizes Exxon’s massive production of greenhouse gas emissions, even when scaled to production as Exxon’s is the largest oil company. This year’s emissions are significantly lower than 2008 but Exxon still produces a lot of waste, even when scaled against production. Exxon has been recently accused for a spill in Brooklyn, New York that was larger in the total amount of oil spilled than the Exxon Valdez, as this spill is estimated at 17-30 million gallons versus the Valdez’s 11 million; the spill has been taking place from the 1800s to 1900s and Exxon has not done anything to address it. 

      </description>
      <categories>
	
      </categories>
	<sources><source><source-text>Green America: Company ID 221</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=221</url><date>20111023122301</date></source><source><source-text>Greenopia</source-text><url>http://http://www.greenopia.com/usa/oil_listing.aspx?ID=6&amp;input=Name-or-product&amp;Listpage=0 </url><date>20111023122301</date></source></sources>
	<links></links>
      <companies>
	<company>
	  <normalized>exxon company, u.s.a.</normalized>
	  <tagged>Exxon</tagged>
	  <address></address>
	  <GCPs><GCP>0077162</GCP></GCPs>
	</company>
	<company>
	  <normalized>Exxon Company, U.S.A.</normalized>
	  <tagged>Exxon</tagged>
	  <address>TX
	  5959 Las Colinas Blvd
	  75039
	  Irving
	  United States</address>
	  <GCPs><GCP>0077162</GCP></GCPs>
	</company>
      </companies>
      <reviews>
        <review><reviewer>insight</reviewer><date>20111023T172300Z</date></review>

      </reviews>
    </evidence>
    <evidence>
      <title>• Delta Air Lines, Inc is a member of the International Air Transport Association (IATA), a global group of airlines and airports.</title>
      <description>
	• Delta Air Lines, Inc is a member of the International Air Transport Association (IATA), a global group of airlines and airports.  The IATA has staunchly opposed plans for a carbon emissions trading system in the European Union that could reduce greenhouse gas emissions and mitigate the effects of global climate change.  The organization has argued that such a scheme would be prohibitively expensive for the airlines and make it more difficult to retain profits. 

      </description>
      <categories>
	<category>
	  <category-name>Environment</category-name>
	</category>
      </categories>
	<sources><source><source-text>Green America: Company ID 400</source-text><url>http://www.greenamerica.org/programs/responsibleshopper/company.cfm?id=400</url><date>20111023122328</date></source><source><source-text>New York Times</source-text><url>http://greeninc.blogs.nytimes.com/2009/02/11/curbing-foreign-airline-emissions-in-europe/</url><date>20111023122328</date></source></sources>
	<links><link><link-text>www.delta.com</link-text><url>http://www.delta.com</url></link></links>
      <companies>
	<company>
	  <normalized></normalized>
	  <tagged>Delta Air Lines</tagged>
	  <address></address>
	  <GCPs></GCPs>
	</company>
      </companies>
      <reviews>